version: '3'

volumes:
  pg_data_prod:
  static_prod:
  media_prod:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_prod:/var/lib/postgresql/data

  backend:
    image: dragonwlad/foodgram_backend
    env_file: .env
    volumes:
      - static_prod:/backend_static
      - media_prod:/app/media
    depends_on:
      - db

  frontend:
    image: dragonwlad/foodgram_frontend
    command: >
      sh -c "cp -r /app/build/. /frontend_static/"
    volumes:
      - static_prod:/frontend_static

  gateway:
    container_name: foodgram_gateway
    image: dragonwlad/foodgram_gateway
    volumes:
      - static_prod:/staticfiles/
      - media_prod:/media/
    ports:
      - 7000:80
    depends_on:
      - backend
