# Generated by Django 3.2.16 on 2023-11-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20231129_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='recipe_in_cart',
            new_name='recipe',
        ),
    ]
