# Generated by Django 3.2.16 on 2023-11-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_recipe_in_cart_cart_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Ингредиент рецепта', 'verbose_name_plural': 'Ингредиенты рецептов'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Тег рецепта', 'verbose_name_plural': 'Теги рецептов'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='user',
        ),
    ]
